### ISSUE TITLE
react-vertical-timeline

### ISSUE THREAD

**Issue by clbenoit** [clbenoit/portfolio#1]
Yo gros,

Suis en galère pour intégrer https://stephane-monnot.github.io/react-vertical-timeline . Dans le projet. On dirait c'est pas compatible Vocs...

On peut mixer des jsx, mdx, tsx etc dans ce genre de projet ?

**Comment by LouiFi** [comment]
Yo bro,

Créer une branche pour cette issue je vais regarder ça.

Mais oui normalement tu peux intégrer n'importe quel compoenent react dedans

**Comment by clbenoit** [comment]
Nice, j'ai crée la branche

**Comment by LouiFi** [comment]
Il est casse gueule son package mdr, je bosse dessus là j'ai pris ma journée

**Comment by clbenoit** [comment]
https://github.com/clbenoit/portfolio/pull/2
